# Vectors and Matrix

## 1. Vectors

In [ ]:
from numpy import array
v1 = array([1, 2, 3])

## Or
import numpy as np
v2=np.array([4, 5, 6])

print(v1,v2)

[1 2 3] [4 5 6]


1. Sum

    c = a + b   => c = (a1 + b1, a2 + b2, a3 + b3) 


In [ ]:
from numpy import array

v1 = array([1, 2, 3])
v2 = array([1, 2, 3])
print(v1)
print(v2)

v3 = v1 + v2
print(v3)

[1 2 3]
[1 2 3]
[2 4 6]


2. Subtraction

c = a − b   =>  c = (a1 − b1, a2 − b2, a3 − b3)

In [98]:
from numpy import array

v1 = array([1, 2, 3])
v2 = array([3, 2, 1])
print(v1)
print(v2)

v3 = v1 - v2
print(v3)

[1 2 3]
[3 2 1]
[-2  0  2]


3. Multiplication

c = a × b => c = (a1 × b1, a2 × b2, a3 × b3)

In [99]:
from numpy import array

v1 = array([1, 2, 3])
v2 = array([3, 2, 1])
print(v1)
print(v2)

v3 = v1 * v2
print(v3)

[1 2 3]
[3 2 1]
[3 4 3]


4. Division

c = a/b => c = (a1 / b1, a2 / b2, a3 / b3)



In [100]:
from numpy import array

v1 = array([1, 2, 3])
v2 = array([3, 2, 1])
print(v1)
print(v2)

v3 = v1 / v2
print(v3)

[1 2 3]
[3 2 1]
[0.33333333 1.         3.        ]


5. Inner Multiplication

c = a · b =>  c = (a1 × b1 + a2 × b2 + a3 × b3)

In [101]:
from numpy import array

v1 = array([1, 2, 3])
v2 = array([3, 2, 1])
print(v1)
print(v2)

v3 = v1 @ v2  # or v1.dot(v2)
print(v3)

[1 2 3]
[3 2 1]
10


6. Multiplication - Scalar

c = s × v => c = (s × v1, s × v2, s × v3)

In [102]:
# vector-scalar multiplication
from numpy import array

v1 = array([1, 2, 3])
s = 0.5

v2 = s * v1
print(v2)

[0.5 1.  1.5]


### 2) Norm = Length

 1. l1

L1(v) = |a1| + |a2| + |a3|

In [103]:
from numpy import array
from numpy.linalg import norm

v1 = array([1, 2, 3])

l1 = norm(v1, 1) # 1 + 2 + 3
print(l1)

6.0


2. l2

L2(v) = sqr ( a1^2 + a2^2 + a3^2)

In [104]:
from numpy import array
from numpy.linalg import norm
from math import sqrt
v2 = array([1, 1, 1, 2, 3])

l2 = norm(v2, 2) # sqrt((1^2) + (1^2) + (1^2) + (2^2) + (3^2))= sqrt( 1 + 1 + 1 + 4 + 9 ) = sqrt(16)
print(l2)

4.0


 ## 2) Matrix

In [105]:
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


2. Sum

In [106]:
from numpy import array

A = array([
[1, 2, 3],
[4, 1, 1]])
print(A)

B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)

C = A + B   
print(C)

[[1 2 3]
 [4 1 1]]
[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [8 6 7]]


In [107]:
# a - b // a * b // a / b

2. Inner Multiplication

In [108]:
from numpy import array

A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)

B = array([
[1, 2],
[3, 4]])
print(B)

C = A @ B # C = A.dot(B)
# A11*B11+A12*B21=1*1+2*3=7    A11*B21+A12*B22=1*2+2*4=10
# A21*B11+A22*B21=3*1+4*3=15   A21*B21+A22*B22=3*2+4*4=22
# A31*B11+A32*B21=5*1+6*3=23   A31*B21+A32*B22=5*2+4*6=34
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]


3. Multiplication - Scalar

In [110]:
from numpy import array

A = array([[1, 2], [3, 4], [5, 6]])
print(A)

b = 0.5
print(b)

C = A * b
print(C)

[[1 2]
 [3 4]
 [5 6]]
0.5
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


4. Multiplication (Vector-Matrix)

In [109]:
from numpy import array

A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)

B = array([0.5, 0.5])
print(B)

C = A@B
print(C)

[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]
[1.5 3.5 5.5]


5) Matrix operations

###### Transpose

In [ ]:
from numpy import array

A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)

C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


###### Inverse

In [ ]:
from numpy import array
from numpy.linalg import inv

A = array([
[1.0, 2.0],
[3.0, 4.0]])
print(A)

B = inv(A)
print(B)

I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


###### Trace

In [ ]:
from numpy import array
from numpy import trace

A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)

B = trace(A) # 1 + 5 + 9
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


###### Determinant

In [1]:
from numpy import array
from numpy.linalg import det

A = array([
[1, 2],
[4, 5]])
print(A)

B = det(A)
print(B)

[[1 2]
 [4 5]]
-2.9999999999999996


6) Type of matrix

###### Square (n=m)

In [ ]:
print(array([[1,2,1],[3,4,2],[4,6,8]]))  # n=m=3

[[1 2 1]
 [3 4 2]
 [4 6 8]]


###### Symmetric (n=m and M=M(T))

In [ ]:
print(array([[1,5,2],[5,0,3],[2,3,4]]))

[[1 5 2]
 [5 0 3]
 [2 3 4]]


###### Triangle

In [ ]:
A= array([[1,0,0],[2,4,0],[4,3,1]])
print(A)
print(A.T)

[[1 0 0]
 [2 4 0]
 [4 3 1]]
[[1 2 4]
 [0 4 3]
 [0 0 1]]


###### Diagonal

In [ ]:
print(array([[1,0,0],[0,4,0],[0,0,5]]))

[[1 0 0]
 [0 4 0]
 [0 0 5]]


###### Identity

In [ ]:
from numpy import identity
I = identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


###### Orthogonal (متعامد)

M. MT = I
--- or --- inv(M)=MT

In [ ]:

from numpy import array
from numpy.linalg import inv

Q = array([
[1, 0],
[0, -1]])
print(Q)

I = Q.dot(Q.T)
print(I)

V = inv(Q)
print(Q.T)
print(V)

[[ 1  0]
 [ 0 -1]]
[[1 0]
 [0 1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
