# Numpy

In [426]:
import numpy as np

x1 = np.random.randint(10, size=6) # 1D array
x2 = np.random.randint(10, size=(3, 4)) # 2D array
x3 = np.random.randint(10, size=(3, 4, 5)) # 3D array

In [427]:
x3

array([[[0, 8, 2, 8, 9],
        [0, 2, 8, 0, 8],
        [7, 5, 2, 2, 8],
        [2, 0, 5, 9, 0]],

       [[9, 8, 0, 7, 5],
        [5, 1, 5, 9, 7],
        [4, 6, 2, 1, 6],
        [2, 8, 6, 0, 6]],

       [[2, 2, 7, 5, 8],
        [6, 1, 3, 4, 9],
        [2, 4, 4, 4, 6],
        [9, 1, 7, 2, 9]]], dtype=int32)

In [428]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [429]:
print("dtype:", x3.dtype)

dtype: int32


In [430]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [432]:
x1

array([8, 7, 1, 5, 1, 4], dtype=int32)

In [433]:
x1[0]

np.int32(8)

In [434]:
x1[-2]

np.int32(1)

In [435]:
x2

array([[9, 3, 3, 2],
       [6, 3, 8, 9],
       [9, 0, 9, 0]], dtype=int32)

In [436]:
x2[0, 0]

np.int32(9)

In [437]:
x2[0, 0] = 12
x2

array([[12,  3,  3,  2],
       [ 6,  3,  8,  9],
       [ 9,  0,  9,  0]], dtype=int32)

In [438]:
x1[0] = 3.14159
x1

array([3, 7, 1, 5, 1, 4], dtype=int32)

### access to subarray

In [439]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [440]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x[5:]

array([5, 6, 7, 8, 9])

In [442]:
x[4:7]

array([4, 5, 6])

In [443]:
x[::2]

array([0, 2, 4, 6, 8])

In [444]:
x[1::2]

array([1, 3, 5, 7, 9])

In [445]:
x[::-1] # reverse the array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [446]:
x2

array([[12,  3,  3,  2],
       [ 6,  3,  8,  9],
       [ 9,  0,  9,  0]], dtype=int32)

In [447]:
x2[:2, :3]# 2 rows, 3 colomns

array([[12,  3,  3],
       [ 6,  3,  8]], dtype=int32)

In [448]:
x2[:3, ::2] 

array([[12,  3],
       [ 6,  8],
       [ 9,  9]], dtype=int32)

In [449]:
x2[::-1, ::-1] #  inverse

array([[ 0,  9,  0,  9],
       [ 9,  8,  3,  6],
       [ 2,  3,  3, 12]], dtype=int32)

In [450]:
print(x2[:, 0]) # first colomn of x2

[12  6  9]


In [451]:
print(x2[0]) #or x2[0, :]

[12  3  3  2]


### Reshaping of Arrays

In [452]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [453]:
x = np.array([1, 2, 3])
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [ ]:
arr=np.repeat([2,3,4],3).reshape(3,3)
print(arr)
np.diag(arr)

[[2 2 2]
 [3 3 3]
 [4 4 4]]


array([2, 3, 4])

In [ ]:
arr.astype('f') #convert to float

array([[5., 5., 4.],
       [5., 2., 1.],
       [0., 8., 5.]], dtype=float32)

## Array Concatenation and Splitting

### 1.Concatenation of arrays

In [454]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [455]:
z = [99, 99, 99]
print(np.concatenate([x, y, z])) # Without increasing the dimension

[ 1  2  3  3  2  1 99 99 99]


In [456]:
np.vstack([x,y]) # Increasing the dimension

array([[1, 2, 3],
       [3, 2, 1]])

In [457]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

In [458]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [459]:
y = np.array([[99],
              [99]])

In [460]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting of arrays

In [461]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 6])
print(x1, x2, x3)

[1 2 3] [99 99  3] [2 1]


In [462]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [463]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [464]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Operators in Numpy  

In [465]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)
print(-(0.5*x + 1) ** 2)
np.add(x, 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]
[-1.   -2.25 -4.   -6.25]


array([2, 3, 4, 5])

In [466]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
3^x = [ 3  9 27]


In [467]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [468]:
data= np.random.random(100)
data

array([0.4618128 , 0.67085319, 0.37812188, 0.26115865, 0.43032374,
       0.39096546, 0.3413906 , 0.75496719, 0.86755852, 0.75279105,
       0.03026383, 0.82760408, 0.46011695, 0.97539623, 0.70726031,
       0.76071363, 0.66087979, 0.11241425, 0.80366947, 0.02116037,
       0.90981051, 0.31925792, 0.97770855, 0.47301074, 0.4414656 ,
       0.39221604, 0.45287025, 0.66913773, 0.61062758, 0.75072216,
       0.76402789, 0.09452389, 0.54434315, 0.51916097, 0.3160128 ,
       0.13370177, 0.68840778, 0.15095046, 0.43033563, 0.58013977,
       0.55811244, 0.87402288, 0.31389953, 0.08921535, 0.96401751,
       0.46579475, 0.315743  , 0.43392966, 0.77132881, 0.92587827,
       0.61989665, 0.07850787, 0.97699694, 0.95665104, 0.65415694,
       0.93947742, 0.06358902, 0.21979721, 0.87517808, 0.79671762,
       0.16703285, 0.84297672, 0.66296179, 0.37451983, 0.97500007,
       0.60896915, 0.71279181, 0.53070575, 0.01481171, 0.91872324,
       0.78624527, 0.86616439, 0.53573419, 0.90974526, 0.91871

In [469]:
np.min(data), np.max(data)

(np.float64(0.014811707997086643), np.float64(0.977708554455482))

In [470]:
M = np.random.random((3, 4))
print(M)

[[0.1743216  0.07427867 0.3770274  0.25612306]
 [0.99721719 0.93259517 0.53514901 0.14015677]
 [0.07707976 0.12227591 0.67247197 0.32981575]]


In [471]:
M.sum()

np.float64(4.688512250788688)

In [472]:
M.min(axis=0)

array([0.07707976, 0.07427867, 0.3770274 , 0.14015677])

In [473]:
M.max(axis=1)

array([0.3770274 , 0.99721719, 0.67247197])

In [474]:
M.argmax()

np.int64(4)

## Sorting Arrays

In [475]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [476]:
print(np.sort(x))

[1 2 3 4 5]


In [477]:
X = np.random.randint(0, 10, (4, 6))
X

array([[1, 1, 8, 1, 8, 0],
       [2, 6, 1, 5, 6, 3],
       [1, 6, 6, 5, 0, 2],
       [2, 0, 0, 2, 2, 5]], dtype=int32)

In [478]:
# sort each column of X
np.sort(X, axis=0)

array([[1, 0, 0, 1, 0, 0],
       [1, 1, 1, 2, 2, 2],
       [2, 6, 6, 5, 6, 3],
       [2, 6, 8, 5, 8, 5]], dtype=int32)

In [479]:
# sort each row of X
np.sort(X, axis=1)

array([[0, 1, 1, 1, 8, 8],
       [1, 2, 3, 5, 6, 6],
       [0, 1, 2, 5, 6, 6],
       [0, 0, 2, 2, 2, 5]], dtype=int32)